### PR TITLE
Skip over ld+json that does not mention whether article is free

### LINKED ISSUE #2355: isArticleFreeFromMicrodataPageConfig_ function depends on script "application/ld+json" order
Currently we have more than one script of "application/ld+json" type.

The function isArticleFreeFromMicrodataPageConfig_ iterates over all scripts of type "application/ld+json" but if the first script does not contain the property "isAccessibleForFree" the iteration stops and it returns false, not iterating over the next scripts.

To reproduce this problem we used the following script order:

```HTML
<script data-schema="Organization" type="application/ld+json">
        {
            "@context": "http:\/\/schema.org",
            "@type": "Organization",
            "name": "Demo app",
            "url": "https:\/\/demo.pt"
        }
    </script>

    <script data-schema="WebPage" type="application/ld+json">
        {
            "@context": "http:\/\/schema.org",
            "@type": "WebSite",
            "name": "Demo app",
            "url": "https:\/\/demo.pt",
            "potentialAction": {
                "@type": "SearchAction",
                "target": "https:\/\/demo.pt\/pesquisa?q={search_term}",
                "query-input": "required name=search_term"
            }
        }
    </script>

    <script type="application/ld+json">
        {
            "@context": "http:\/\/schema.org",
            "@type": "NewsArticle",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "123"
            },
            "headline": "Head",
            "description": "Desc",
            "publisher": {
                "@type": "Organization",
                "name": "DEMO APP"
            },
            "isPartOf": {
                "@type": [
                    "CreativeWork",
                    "Product"
                ],
                "name": "DEMO APP",
                "productID": "***:showcase"
            },
            "isAccessibleForFree": true
        }
    </script>
```
And isArticleFreeFromMicrodataPageConfig_ will return false. If we change the order to:
```HTML
<script type="application/ld+json">
        {
            "@context": "http:\/\/schema.org",
            "@type": "NewsArticle",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "123"
            },
            "headline": "Head",
            "description": "Desc",
            "publisher": {
                "@type": "Organization",
                "name": "DEMO APP"
            },
            "isPartOf": {
                "@type": [
                    "CreativeWork",
                    "Product"
                ],
                "name": "DEMO APP",
                "productID": "***:showcase"
            },
            "isAccessibleForFree": true
        }
    </script>

<script data-schema="Organization" type="application/ld+json">
        {
            "@context": "http:\/\/schema.org",
            "@type": "Organization",
            "name": "Demo app",
            "url": "https:\/\/demo.pt"
        }
    </script>

    <script data-schema="WebPage" type="application/ld+json">
        {
            "@context": "http:\/\/schema.org",
            "@type": "WebSite",
            "name": "Demo app",
            "url": "https:\/\/demo.pt",
            "potentialAction": {
                "@type": "SearchAction",
                "target": "https:\/\/demo.pt\/pesquisa?q={search_term}",
                "query-input": "required name=search_term"
            }
        }
    </script>
```
isArticleFreeFromMicrodataPageConfig_ will return true as expected.

https://github.com/subscriptions-project/swg-js/blob/b53bb24e210593436316f047a9c91a1a81386703/src/utils/gaa.js#L1990

### PR DESCRIPTION
**Pull request by ChrisAntaki**
Fixes #2355

### CODE REVIEW

File: src/utils/gaa-test.js [hunk 1]
```diff
@@ -47,8 +47,7 @@ const PRODUCT_ID = 'scenic-2017.appspot.com:news';
 const IFRAME_URL = 'https://localhost/gsi-iframe';
 const GOOGLE_3P_AUTH_URL = 'https://fabulous-3p-authserver.glitch.me/auth';
 const CASL_URL = 'https://example-casl.com';
-const GOOGLE_API_CLIENT_ID =
-  '520465458218-e9vp957krfk2r0i4ejeh6aklqm7c25p4.apps.googleusercontent.com';
```
Comment (ChrisAntaki) [inline src/utils/gaa-test.js:51]: I noticed this realistic Client ID was preventing me from committing changes to the file. Luckily, it doesn't need to be realistic

**Review by jpettitt — APPROVED** [review]
